# This is the main configuration file of this minigame.
# I am going to improve some things in the future.
# I hope you will like it!
# If you have problems contact me:
#   - discord: florixak
#   - github: https://github.com/florixak

settings:

  # Expanding plugins
  addons:
    use-Vault: false # Enable integration with Vault for economy support
    use-LuckPerms: false # Enable integration with LuckPerms for permission management
    use-ProtocolLib: true # Enable integration with ProtocolLib for enhanced compatibility
    use-PlaceholderAPI: true # Enable integration with PlaceholderAPI for custom placeholders
    use-DecentHolograms: true # Enable integration with DecentHolograms for hologram support

  bungee-mode:
    enabled: false # Enable BungeeCord support
    lobby-server: "lobby" # Name of the lobby server

  # MySQL database
  # Warning: Do not forget to create %database% before starting the server
  mysql:
    enabled: false # Enable MySQL database integration
    host: "localhost" # MySQL server host
    port: "3306" # MySQL server port
    database: "minigame" # MySQL database name
    table: "minigame"
    username: "root" # MySQL username
    password: "" # MySQL password

  # Game settings
  game:
    no-explosions: false # Globally disable explosions
    explode-block-destroy: true # Allow explosions to destroy blocks
    spawn-monsters: false # Allow monsters to spawn
    monsters-attack: false # Allow monsters to attack players

    players-to-start: 2 # Minimum number of players to start the game
    starting-message-at: 10 # Time in seconds to display starting message

    # Countdowns for different game phases
    countdowns:
      starting: 15 # Countdown for game start in seconds
      ending: 15 # Countdown for game end in seconds

  # Team settings
  teams:
    friendly-fire: false # Allow friendly fire within teams

  # Kit settings
  kits:
    enabled: true # Enable kits
    bought-forever: true # Kits are bought permanently

  # Perk settings
  perks:
    enabled: true # Enable perks
    bought-forever: true # Perks are bought permanently

  # Lobby settings
  # Rename your lobby files to these world names, or set it manually
  lobby:
    world: "lobby" # Name of the lobby world
    x: 0.0 # X coordinate of the lobby spawn
    y: 100.0 # Y coordinate of the lobby spawn
    z: 0.0 # Z coordinate of the lobby spawn
    yaw: 0.0 # Yaw of the lobby spawn
    pitch: 0.0 # Pitch of the lobby spawn

  # Statistics settings
  statistics:
    # Starting money for each player
    starting-money: 100
    starting-tokens: 0

    level:
      # Players will gain xp and increase their level
      starting-level: 0 # Starting level
      starting-required-exp: 100.0 # Experience required for first level
      exp-multiplier: 3.75 # Multiplier for experience required for each level

    player-stats:
      display-item: PLAYER_HEAD # Item to display player stats
      slot: 10 # Slot for player stats
      custom-name: "&a%minigame_player%" # Custom name for player stats
      lore:
        - "&fLevel: &a%minigame_level%"
        - "&fRequired EXP: &a%minigame_required-exp%"
        - "&fMoney: &a%minigame_money%"
        - " "
        - "&fWins: &a%minigame_total-wins%"
        - "&fLosses: &a%minigame_total-losses%"
        - "&fKills: &a%minigame_total-kills%"
        - "&fAssists: &a%minigame_total-assists%"
        - "&fDeaths: &a%minigame_total-deaths%"
        - "&fKillstreak: &a%minigame_killstreak%"
        - "&fGames Played: &a%minigame_games-played%"
    top-stats:
      types:
        WINS:
          display-name: "Wins" # Display name for top stats
          display-item: GOLDEN_APPLE # Item to display top stats
          slot: 12 # Slot for top stats
        KILLS:
          display-name: "Kills" # Display name for top stats
          display-item: IRON_SWORD # Item to display top stats
          slot: 13 # Slot for top stats
        DEATHS:
          display-name: "Deaths" # Display name for top stats
          display-item: SKULL # Item to display top stats
          slot: 14 # Slot for top stats
        ASSISTS:
          display-name: "Assists" # Display name for top stats
          display-item: BOW # Item to display top stats
          slot: 15 # Slot for top stats
        LOSSES:
          display-name: "Losses" # Display name for top stats
          display-item: COAL # Item to display top stats
          slot: 16 # Slot for top stats
        KILLSTREAK:
          display-name: "Killstreak" # Display name for top stats
          display-item: DIAMOND_SWORD # Item to display top stats
          slot: 21 # Slot for top stats
        GAMES-PLAYED:
          display-name: "Games Played" # Display name for top stats
          display-item: PAPER # Item to display top stats
          slot: 22 # Slot for top stats
        LEVEL:
          display-name: "Level" # Display name for top stats
          display-item: GOLDEN_HELMET # Item to display top stats
          slot: 23 # Slot for top stats
      custom-name: "&a%top-stats-mode%"
      lore:
        - "&7------===========------"
        - "&a1. &f%minigame_top-1%"
        - "&a2. &f%minigame_top-2%"
        - "&a3. &f%minigame_top-3%"
        - "&a4. &f%minigame_top-4%"
        - "&a5. &f%minigame_top-5%"
        - "&7------===========------"
      hologram: # DecentHolograms plugin required
        - "    &a%top-stats-mode%    "
        - "&7------===========------"
        - "&a1. &f%minigame_top-1%"
        - "&a2. &f%minigame_top-2%"
        - "&a3. &f%minigame_top-3%"
        - "&a4. &f%minigame_top-4%"
        - "&a5. &f%minigame_top-5%"
        - "&7------===========------"

  # Reward settings
  rewards:
    multiplier: 1.0 # Multiplier for rewards (coins, experience) 2 = double rewards, 3 = triple rewards
    kill:
      coins: 30 # Money reward for a kill
      exp: 60 # Experience reward for a kill
      uhc-exp: 25 # UHC experience reward for a kill
    assist:
      coins: 10 # Money reward for an assist
      exp: 5 # Experience reward for an assist
      uhc-exp: 10 # UHC experience reward for an assist
    win:
      coins: 150 # Money reward for a win
      uhc-exp: 200 # UHC experience reward for a win
    lose:
      coins: 50 # Money reward for a loss
      uhc-exp: 50 # UHC experience reward for a loss
    activity:
      enabled: false # Enable activity rewards
      coins: 10 # Money reward for activity
      uhc-exp: 20 # UHC experience reward for activity
      period: 300 # Time period in seconds for activity rewards
    level-up:
      base-reward: 10 # Base reward for leveling up
      reward-coefficient: 1.2 # %base-reward% + (%reward-coefficient% ^ %uhc-level%)

  # End game commands - commands executed at the end of the game
  end-game-commands: [ ]

  # Tablist settings
  tablist: # Enable custom tablist (requires ProtocolLib)
    update-interval: 10 # Update interval in seconds
    lobby:
      enabled: true
      header:
        - "&e&lMinigame\n &7%date%\n"
        - "&6&lM&e&linigame\n &7%date%\n"
        - "&e&lM&6&li&e&lnigame\n &7%date%\n"
        - "&e&lMi&6&ln&e&ligame\n &7%date%\n"
        - "&e&lMin&6&li&e&lgame\n &7%date%\n"
        - "&e&lMini&6&lg&e&lame\n &7%date%\n"
        - "&e&lMinig&6&la&e&lme\n &7%date%\n"
        - "&e&lMiniga&6&lm&e&le\n &7%date%\n"
        - "&e&lMinigam&6&le\n &7%date%\n"
        - "&e&lMinigame\n &7%date%\n"
        - "&6&lMinigame\n &7%date%\n"
      player-list: "&7[%level%] &f%player%" # Player list format for solo mode
      footer: "\n&7www.your-server.com" # Footer text for tablist
    ingame:
      enabled: true
      header:
        - "&e&lMinigame\n &7%arena_name%\n"
        - "&6&lM&e&linigame\n &7%arena_name%\n"
        - "&e&lM&6&li&e&lnigame\n &7%arena_name%\n"
        - "&e&lMi&6&ln&e&ligame\n &7%arena_name%\n"
        - "&e&lMin&6&li&e&lgame\n &7%arena_name%\n"
        - "&e&lMini&6&lg&e&lame\n &7%arena_name%\n"
        - "&e&lMinig&6&la&e&lme\n &7%arena_name%\n"
        - "&e&lMiniga&6&lm&e&le\n &7%arena_name%\n"
        - "&e&lMinigam&6&le\n &7%arena_name%\n"
        - "&e&lMinigame\n &7%arena_name%\n"
        - "&6&lMinigame\n &7%arena_name%\n"
      player-list: "&7[%level%] %team% &f%player%" # Player list format for team mode
      footer: "\n&7www.your-server.com" # Footer text for tablist

  # Selectors

  title:
    enabled: true # Enable title messages like victory or lose
    fade-in: 2 # Fade in time in seconds
    stay: 3 # Stay time in seconds
    fade-out: 2 # Fade out time in seconds

  sounds:
    # List of sounds for different game events
    # If you want do disable sound, set it to NONE
    started:
      sound: ENTITY_PLAYER_LEVELUP
      volume: 0.5
      pitch: 1.0
    starting:
      sound: BLOCK_STONE_BUTTON_CLICK_ON
      volume: 0.5
      pitch: 1.0
    win:
      sound: ENTITY_FIREWORK_ROCKET_BLAST
      volume: 0.5
      pitch: 1.0
    game-over:
      sound: ENTITY_ENDER_DRAGON_GROWL
      volume: 0.5
      pitch: 1.0
    level-up:
      sound: ENTITY_PLAYER_LEVELUP
      volume: 0.5
      pitch: 1.0
    kill:
      sound: ENTITY_LIGHTNING_BOLT_IMPACT
      volume: 0.1
      pitch: 1.0
    death:
      sound: ENTITY_LIGHTNING_BOLT_IMPACT
      volume: 0.1
      pitch: 1.0
    assist:
      sound: NONE
      volume: 0.1
      pitch: 1.0
    select-buy: # Sound for selecting and buying kits, perks
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.5
      pitch: 1.0
    purchase-cancel:
      sound: BLOCK_ANVIL_BREAK
      volume: 0.5
      pitch: 1.0
    quest-complete:
      sound: ENTITY_PLAYER_LEVELUP
      volume: 0.5
      pitch: 1.0

  # Chat
  chat:
    # Chat format placeholders:
    # %player% - Name of player
    # %uhc-level% - UHC level of player
    # %luckperms-prefix% - If luckperms are allowed in config, displays player's prefix
    # %message% - Sent message
    # %level% - Player level
    # %team% - Team name
    lobby-format: "&7[%minigame_level%] %minigame_team% &f%minigame_player% &7» &f%message%" # Format for chat messages in the lobby or in the solo mode
    global-format: "&6[GLOBAL] &7[%minigame_level%] %minigame_team% &f%minigame_player% &7» &f%message%" # Format for global chat messages, with ! before message and teams enabled
    teams-format: "&6[TEAM] &7[%minigame_level%] %minigame_team% &f%minigame_player% &7» &f%message%" # Format for team chat messages
    solo-format: "&7[%minigame_level%] &f%minigame_player% &7» &f%message%" # Format for chat messages in-game
    dead-format: "&7[SPECTATOR] [%minigame_level%] %minigame_team% &7%minigame_player% » %message%" # Format for chat messages from dead players

    # List of commands blocked in chat
    # It is not perfect, it has some flaws but it works in most cases
    blocked-commands:
      - /pl
      - /plugins
      - /lp
      - /lp help
      - /lp editor
      - /luckperms
      - /luckperms editor
      - /luckperms help
      - /paper
      - /plugins
      - /paper
      - /plugins
      - /paper
      - /gm
      - /gmc
      - /gms
      - /gmsp
      - /gma
      - /gamemode
      - /gamemode 0
      - /gamemode 1
      - /gamemode 2
      - /gamemode 3
      - /gamemode c
      - /gamemode s
      - /gamemode a
      - /gamemode sp
      - /gamemode creative
      - /gamemode survival
      - /gamemode adventure
      - /gamemode spectator
      - /gm c
      - /gm s
      - /gm a
      - /gm sp
      - /gm spec
      - /give
      - /kill
      - /?