name: MinigameTemplate
version: '${project.version}'
main: me.florixak.minigametemplate.MinigameTemplate
api-version: '1.21'
author: FloriXak
description: A template for creating minigames.
softdepend: [ PlaceholderAPI, ProtocolLib, Vault, DecentHolograms, LuckPerms ]

commands:
  minigame:
    description: Main command for MinigameTemplate.
    aliases: [ mgt ]
  join:
    description: Join the minigame.
  leave:
    description: Leave the minigame.
  anvil:
    description: Open the anvils GUI.

