name: MinigameTemplate
version: '${project.version}'
main: me.florixak.minigametemplate.MinigameTemplate
api-version: '1.21'
author: FloriXak
description: A template for creating minigames.
softdepend: [ PlaceholderAPI, ProtocolLib, Vault, DecentHolograms, LuckPerms ]

commands:

