name: MinigameTemplate
version: '${project.version}'
main: me.florixak.minigametemplate.MinigameTemplate
api-version: '1.13'
author: FloriXak
description: A template for creating minigames.
softdepend: [ PlaceholderAPI, ProtocolLib, Vault, DecentHolograms, LuckPerms ]

commands:
  minigame:
    description: Main command for MinigameTemplate.
  arena:
    description: Arena command for MinigameTemplate.
    aliases: [ arenas ]
  join:
    description: Join the minigame.
  leave:
    description: Leave the minigame.
  workbench:
    description: Open the workbench GUI.
  anvil:
    description: Open the anvils GUI.

